module.exports={
    INSERT : 'INSERT INTO BLOG (MEMBER_SEQ,MAIN_IMG,TITLE,CONTENT,REGP_IP,REGP_SEQ)VALUES(?,?,?,?,?,?)',
    DELETE : 'DELETE FROM BLOG WHERE BLOG_SEQ = ?',
    UPDATE : '',
    LIST   : 'SELECT BLOG_SEQ,MAIN_IMG,TITLE,CONTENT FROM BLOG WHERE MEMBER_SEQ = ?',
}